/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    LoginPanel: typeof import('./src/components/LoginPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchRecord: typeof import('./src/components/SearchRecord/index.vue')['default']
    Switch: typeof import('./src/components/ui/switch/Switch.vue')['default']
    Zhj_input: typeof import('./src/components/zhj_ui/zhj_input.vue')['default']
  }
}
